language: node_js
node_js:
- "stable"

sudo: false

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli#develop
- cd /tmp
- chmod +x /home/travis/build/appdevdesigns/opstool-mpd-stewardwise/test/setup/install.sh
- /home/travis/build/appdevdesigns/opstool-mpd-stewardwise/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-mpd-stewardwise .
- cd opstool-mpd-stewardwise
- npm install

script:
- npm test
 
